/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uQuXVwNykZf
 */
import { CardTitle, CardDescription, CardHeader, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function card() {
  return (
    <Card>
      <CardHeader className="flex items-start relative">
        <div className="flex-1">
          <CardTitle>Meeting Notes</CardTitle>
          <CardDescription>Notes from the weekly meeting.</CardDescription>
        </div>
        <div className="flex flex-col justify-start space-y-1 text-sm">
          <div className="absolute top-0 right-0">
            <Button className="w-auto" size="none" variant="ghost">
              <StarIcon className="h-4 w-4" />
              <span className="sr-only">Favorite</span>
            </Button>
          </div>
          <div className="absolute bottom-0 right-0">
            <Button className="w-auto" size="none" variant="ghost">
              <FileEditIcon className="h-4 w-4" />
              <span className="sr-only">Edit</span>
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardFooter className="text-xs">
        <span className="opacity-70">Created 2 hours ago</span>
      </CardFooter>
    </Card>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}
